<h4 class="widgettitle">Form Elements</h4>
<div class="widgetcontent">
    <?php $form->prepare(); ?>
    <?php echo $this->form()->openTag($form); ?>
    <?php $element = $form->get('first_name'); ?>

    <?php foreach ($form as $element): ?>
        <div class="par control-group <?php echo count($element->getMessages()) > 0 ? 'error' : '' ?>">
            <label for="inputInfo" class="control-label"><?php echo $element->getOption('label'); ?></label>
            <div class="controls">
                <?php echo $this->formElement($element); ?>
                <span class="help-inline"><?php echo $this->formElementErrors($element); ?></span>
            </div>
        </div><!--par-->
    <?php endforeach; ?>

    <p class="stdformbutton">
        <button class="btn btn-primary">Submit Button</button>
        <button class="btn" type="reset">Reset Form</button>
    </p>
</div>