Hi! My name is zf2 generator <br>
Sole purpose of my creation is to assist you so don't hesitate to use me<br>
Please note that so far I am only available for in-house use of Coeus Solutions<br>
So! please don't upload me on your staging and production servers or I will make your application vulnerable<br>
<br><br><br>

Today I can do following jobs for you<br>
<ul>
    <li><a href='<?php echo $this->url('generator', array('action' => 'form')) ?>'>Generate Form</a></li>
    <li><a href='<?php echo $this->url('generator', array('action' => 'module')) ?>'>Generate Module</a></li>
    <li><a href='<?php echo $this->url('generator', array('action' => 'controller')) ?>'>Generate Controller</a></li>
</ul>