<form method="post">
    <div class="field">
        <label>Module Name :</label>
        <input type="text" name="module_name" />
    </div>
    <div class="field">
        <label>Include Controller :</label>
        <input type="checkbox" name="create_controller" />
    </div>
    <br><br>
    <div class="field">
        <label>Controller Name</label>
        <input type="text" name="controller_name" /> (Leave empty to generate controller with module name)
    </div>
    <br><br>
    <div class="field">
        <input type="submit" value="Generate Module" /> 
    </div>
    
</form>